apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
    purpose: helm
    tier: web
spec:
    replicas: {{ .Values.deployment.replicas }}
    selector:
      matchLabels:
        app: nginx
        purpose: helm
    template:
      metadata:
        labels:
          app: nginx
          purpose: helm
      spec:
        containers:
        - name: nginx
          image: nginx: {{ .Values.image.version }}