apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense 
  labels:
    component: backend
    tier: app
    project: expense
spec:
  replicas: {{ .Values.deployment.replicas}}
  selector:
    matchLabels:
      component: backend
      tier: app
      project: expense
  template:
    metadata:
      labels:
        component: backend
        tier: app
        project: expense
    spec:
      containers:
      - name: backend
        image: joindevops/backend:{{ .Values.deployment.imageVersion}}
        envFrom:
        - configMapRef:
           name: backend